version: '3'

services:


  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: main
      TRANSACTIONS_PER_SECOND: 1000

  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: main
      VALID_TOPIC: valid
      FRAUD_TOPIC: fraud

networks:
  default:
    external:
      name: kafka-network
